"""3add_columns_todos_user

Revision ID: 0ec9d65f55f9
Revises: 49520d71413b
Create Date: 2024-05-13 16:00:07.153646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec9d65f55f9'
down_revision: Union[str, None] = '49520d71413b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'todos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('todos', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
