"""add_column_todos_users

Revision ID: 6ab7c5dd75f8
Revises: 10b2a4c4cc61
Create Date: 2024-05-13 15:39:43.118325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab7c5dd75f8'
down_revision: Union[str, None] = '10b2a4c4cc61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
