"""1add_column_todos_users

Revision ID: 71b9921bc86b
Revises: e2f22ea1e2ad
Create Date: 2024-05-13 15:44:55.130816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b9921bc86b'
down_revision: Union[str, None] = 'e2f22ea1e2ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
