"""create_column_create_update_todo

Revision ID: 7c58fa9c2e49
Revises: ce1aa55d69e5
Create Date: 2024-05-15 11:51:38.448944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c58fa9c2e49'
down_revision: Union[str, None] = 'ce1aa55d69e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
