"""4add_columns_todos_user

Revision ID: 8d0f7f00e033
Revises: 0ec9d65f55f9
Create Date: 2024-05-13 16:02:49.198725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d0f7f00e033'
down_revision: Union[str, None] = '0ec9d65f55f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
