"""create_column_descricao

Revision ID: b4c53d817b8d
Revises: 98336c998a82
Create Date: 2024-05-13 14:47:57.382618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4c53d817b8d'
down_revision: Union[str, None] = '98336c998a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('descricao', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'descricao')
    # ### end Alembic commands ###
