"""update columns User.todos and Todo.user

Revision ID: ce1aa55d69e5
Revises: 407139ae34e0
Create Date: 2024-05-13 16:53:38.350701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce1aa55d69e5'
down_revision: Union[str, None] = '407139ae34e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
