"""add_column_todos_users

Revision ID: e2f22ea1e2ad
Revises: 6ab7c5dd75f8
Create Date: 2024-05-13 15:43:15.941731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f22ea1e2ad'
down_revision: Union[str, None] = '6ab7c5dd75f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
